const actors = [
    { first_name: 'William', last_name: 'Hartnell', tenure_start: 1963, tenure_end: 1966 },
    { first_name: 'Patrick', last_name: 'Troughton', tenure_start: 1966, tenure_end: 1969 },
    { first_name: 'Jon', last_name: 'Pertwee', tenure_start: 1970, tenure_end: 1974 },
    { first_name: 'Tom', last_name: 'Baker', tenure_start: 1974, tenure_end: 1981 },
    { first_name: 'Peter', last_name: 'Davison', tenure_start: 1981, tenure_end: 1984 },
    { first_name: 'Colin', last_name: 'Baker', tenure_start: 1984, tenure_end: 1986 },
    { first_name: 'Sylvester', last_name: 'McCoy', tenure_start: 1987, tenure_end: 1989 },
    { first_name: 'Paul', last_name: 'McGann', tenure_start: 1996, tenure_end: 1996 },
    { first_name: 'John', last_name: 'Hurt', tenure_start: 2013, tenure_end: 2013 },
    { first_name: 'Christopher', last_name: 'Eccelston', tenure_start: 2005, tenure_end: 2005 },
    { first_name: 'David', last_name: 'Tennant', tenure_start: 2005, tenure_end: 2010 },
    { first_name: 'Matt', last_name: 'Smith', tenure_start: 2010, tenure_end: 2013 },
    { first_name: 'Peter', last_name: 'Capaldi', tenure_start: 2013, tenure_end: 2017 },
    { first_name: 'Jodie', last_name: 'Whittaker', tenure_start: 2017, tenure_end: null },
];

const topRated = [
    { title: 'Blink', actor: 'David Tennant' },
    { title: 'Heaven Sent', actor: 'Peter Capaldi' },
    { title: 'Forest of the Dead', actor: 'David Tennant' },
    { title: 'Silence in the Library', actor: 'David Tennant' },
    { title: 'The Day of the Doctor', actor: 'Matt Smith, David Tennant' },
    { title: 'Doomsday', actor: 'David Tennant' },
    { title: 'The Girl in the Fireplace', actor: 'David Tennant' },
    { title: 'Vincent and the Doctor', actor: 'Matt Smith' },
    { title: 'Journey\'s End', actor: 'David Tennant' },
    { title: 'The Big Bang', actor: 'Matt Smith' },
    { title: 'The Empty Child', actor: 'Christopher Eccleston' },
    { title: 'The Family of Blood', actor: 'David Tennant' },
    { title: 'World Enough and Time', actor: 'Peter Capaldi' },
    { title: 'A Good Man Goes to War', actor: 'Matt Smith' },
    { title: 'The Angels Take Manhattan', actor: 'Matt Smith' },
    { title: 'The Doctor Dances', actor: 'Christopher Eccleston' },
    { title: 'The Doctor\s Wife', actor: 'Matt Smith' },
    { title: 'The Name of the Doctor', actor: 'Matt Smith' },
    { title: 'The Night of the Doctor', actor: 'Paul McGann' },
    { title: 'The Pandorica Opens', actor: 'Matt Smith' },
    { title: 'The Parting of Ways', actor: 'Christopher Eccleston' },
    { title: 'The Stolen Earth', actor: 'David Tennant' },
    { title: 'Human Nature', actor: 'David Tennant' },
    { title: 'Listen', actor: 'Peter Capaldi' },
    { title: 'Midnight', actor: 'David Tennant' },
];
